### ISSUE TITLE
pre_data_rl.py error

### ISSUE THREAD

**Issue by cgh2797** [Xyqii/RNN_generator#2]
![캡처1](https://user-images.githubusercontent.com/19909579/95419443-9f653b00-0974-11eb-98ac-e984e1e31c34.PNG)

The error seems to be due to this...
there's no ']' in tralist.

**Comment by Xyqii** [comment]
Thanks for your attention. The key '[' seems to be not in the dictionary of tokens.
The error may occur when new tokens are found in data used for transfer learning.
Building a dictionary with all the training data may solve the problem.

**Comment by cgh2797** [comment]
Solved the problem in a simple way

    dicoftokens['[']=32
    dicoftokens[']'] = 33
    dicoftokens['@'] = 34
    dicoftokens['/'] = 35
    dicoftokens['\\'] = 36
    dicoftokens['H'] = 37
