### ISSUE TITLE
about Train.txt data size

### ISSUE THREAD

**Issue by cgh2797** [Xyqii/RNN_generator#3]
In your paper, it says 7577 molecules in DrugBank.

I can't understand, why there exist 77279 molecules in train.txt???

**Comment by cgh2797** [comment]
I am also curious about what criteria was selected when selecting train data.

**Comment by Xyqii** [comment]
The details of data preperation are described in the methods section of our paper. 
Randomized SMILES sequences were used to train our models, so there are more sequences.
