### ISSUE TITLE
pre_data.py problem

### ISSUE THREAD

**Issue by cgh2797** [Xyqii/RNN_generator#4]
After randomly extracting 100,000 data from pubchem, we want to use it in pre_data.py(train.txt).

I changed train.txt to 100,000 pieces of data randomly picked from pubchem.

However, there was a problem.
The "findsametok" of __main__ does not complete.
This means that "a = a|set(ST.tokenize(smi))" of the "findsametok" function has not been completed.

No error message is displayed, and the command of findsametok function is not executed for several days.

What am I doing wrong?

**Comment by Xyqii** [comment]
Some tokens in your data may not be in the pre-defined token list of 'atoms+special'. Adding those undefined tokens may solve the problem.

**Comment by cgh2797** [comment]
Among the data I have, some of the smiles are too long.

That could be a problem, so I tried running it again with the max_smiles length set to 100, but it doesn't solve the problem.

As you advise, it seems like a problem caused by predefined tokens.
I have no idea what token to add to the pre-defined token.

How did you calculate the pre-defined token?
Can you help me?

**Comment by Xyqii** [comment]
Adding 'print i' after line 80 helps check each sequence. Sequences containing undefined tokens will cause endless loops. Those sequences can be checked manually to find new tokens.

**Comment by cgh2797** [comment]
thank you for the reply.

But I can't run line 80 of pre_data.py.
Runs up to line 69, and an infinite loop at line 70.

**Comment by cgh2797** [comment]
Thanks for the answer.

The problem was solved by adding tokens one by one by printing (smi) under line 47.

Since it's a "special token", can I add it to SmiTok's special?

**Comment by Xyqii** [comment]
Yes : )
